### ISSUE TITLE
Không thể tìm kiếm ngay lúc này

### ISSUE THREAD

**Issue by qweenng** [phamleduy04/chatvoinguoila#21]
Bot mất option end chat và chỉ còn 3 lựa chọn Tìm kiếm, Báo cáo lỗi và Báo cáo người khác thôi ạ. Khi mình bấm Tìm kiếm thì bị báo là “Bạn không thể tìm kiếm ngay lúc này!”
Btw, cảm ơn bạn vì project cực xịn này nhé!

**Comment by phamleduy04** [comment]
@qweenng ID của bạn là gì? Bạn có thể nhắn "id" cho bot để biết ID của mình. 
<img width="634" alt="Screen Shot 2021-02-22 at 1 55 49 PM" src="https://user-images.githubusercontent.com/32657584/108762409-abadf700-7515-11eb-8463-6e9537600bf1.png">

**Comment by qweenng** [comment]
@phamleduy04 ID của mình là: 4043174425706846

**Comment by phamleduy04** [comment]
@qweenng hiện tại bạn đang match với 1 người nhưng có thể người ấy k trả lời bạn hay sao ấy.

Còn cách để exit thì bạn chỉ nhắn "exit" là nó sẽ kết thúc giúp cho bạn.
![image](https://user-images.githubusercontent.com/32657584/108791151-03fbed80-7544-11eb-8242-1606c0a6a902.png)

**Comment by phamleduy04** [comment]
Nếu bạn có update gì cứ comment ở đây nhé xD

**Comment by qweenng** [comment]
Aw mình làm được rồi, cảm ơn bạn nhiều nhennnnn 👍

**Comment by phamleduy04** [comment]
không có gì, chúc bạn 1 ngày vui vẻ nhó xD
