### ISSUE TITLE
Ngrok Tunnel bị hết hạn

### ISSUE THREAD

**Issue by ngotuananh101** [phamleduy04/chatvoinguoila#38]
Bot của mình chạy được mấy phút thì không dùng được nữa do link Ngrok bị hết hạn

**Comment by phamleduy04** [comment]
việc sử dụng ngrok chỉ để test/dev thôi bạn nhé, nếu bạn có ý định đem lên production thì hãy sử dụng các dịch vụ như repl.it hay heroku để host nhé.
